### PR TITLE
Add phpstan/psalm config files

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
You mean phpstan not phpunit

**Comment by OskarStark** [comment]
@core23 can you please check why Psalm and PHPStan are failing? Thanks

**Comment by jordisala1991** [comment]
I found why: https://github.com/sonata-project/dev-kit/pull/1203/files

**Comment by jordisala1991** [comment]
This commits need to be integrated in the dev-kit PR

**Comment by VincentLanglet** [comment]
Why did you close this @jordisala1991 ?

See https://github.com/sonata-project/SonataBlockBundle/pull/771

**Comment by jordisala1991** [comment]
Sorry I thought I could handle it on the dev-kit Pr

**Comment by OskarStark** [comment]
@core this PR was against dev-kit branch. Can you please change the base to `3.x`? Thanks

**Pull request closed without merging**
