### PR TITLE
Remove BaseBlockService

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this can't be done completly without a BC break.

## Changelog

```markdown
### Added
- Added `AbstractAdminBlockService`

### Changed
- Moved general block methods to `AbstractBlockService`

### Removed
- Removed `BaseBlockService`
```

## To do

- [X] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

## Subject

The class `BaseBlockService` doesn't match the correct naming convention and starts with `Base` instead of `Abstract`. The `BaseBlockService` class contains special methods for the admin bundle, so this were moved to the new `AbstractAdminBlockService` class.

### BC Break

Because the class `AbstractBlockService` exists, we can't move all methods and the constructor to abstract class without a break. Our bundles don't use the class `AbstractBlockService` at the moment, but someone else could do it.

### CODE REVIEW

**Comment by core23** [comment]
Please leave your feedback to this change. If you're okay with it, I would try to create a PR for the stable branch with some deprecation warnings.

**Comment by core23** [comment]
What dou you think @OskarStark @greg0ire @Soullivaneuh ? Should we remove the `BaseBlockService` and create a new `AbstractAdminBlockService`?

**Comment by greg0ire** [comment]
What about having a `Sonata\BlockBundle\Bridge\AdminBundle\Block` namespace instead? Wouldn't it make things a bit clearer?

**Comment by core23** [comment]
> What about having a `Sonata\BlockBundle\Bridge\AdminBundle\Block` namespace instead? Wouldn't it make things a bit clearer?

IMO, this not a really a bridge, because it's no abstraction of a concreate implementation.

**Comment by core23** [comment]
Maybe move the `AbstractAdminBlockService` to the admin bundle instead?

**Comment by rande** [comment]
Cannot we have a BC layer ? This might break a lot of block in other bundles

**Comment by core23** [comment]
Closing this in favor of https://github.com/sonata-project/SonataBlockBundle/pull/328

**Pull request closed without merging**
