### PR TITLE
Fix Italian translations

### PR DESCRIPTION
**Pull request by gremo**
## Subject

I am targeting this branch, because this is a minor fix.

## Changelog

```markdown
### Fixed
- Italian translation keys from `sonata.block.*` to `sonata.block.service.*`
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Can you also fix nl:
https://github.com/sonata-project/SonataBlockBundle/blob/5.x/src/Resources/translations/SonataBlockBundle.nl.xliff

and ru:
https://github.com/sonata-project/SonataBlockBundle/blob/5.x/src/Resources/translations/SonataBlockBundle.ru.xliff

Thnaks

**Comment by gremo** [comment]
@VincentLanglet sure, in another PR I guess?

**Comment by VincentLanglet** [comment]
This one or another, as you want

**Comment by gremo** [comment]
@VincentLanglet can you merge this and the other, as I can cleanup my things? thanks! There is also a minor fix in PageBundle too...

**Pull request merged**
