### PR TITLE
Merge 3.x into 4.x

### PR DESCRIPTION
**Pull request by wbloszyk**
Most of change was add in #720

### CODE REVIEW

**Comment by jordisala1991** [comment]
You are mergin again already merged code

**Comment by wbloszyk** [comment]
image

Can you explain this?

**Comment by jordisala1991** [comment]
I think I fucked up on the merge because I didnt add all the commits, just the merge one

**Comment by jordisala1991** [comment]
Anyway your changes seem fine (it were on 3.x), so maybe is a good idea to restore the correct commit history

**Comment by wbloszyk** [comment]
> I think I fucked up on the merge because I didnt add all the commits, just the merge one

Correct. It is must be fix, otherwise auto-merge will be impossible. 

BTW. Like I wrote on slack, yours changes was very helpful.

**Comment by jordisala1991** [comment]
It took me some time to merge all the files, shame that I did not do it correctly

**Comment by greg0ire** [comment]
Done, thanks @wbloszyk !

**Comment by jordisala1991** [comment]
I need to fix the SonataAdmin merge too, not sure if dev kit will be able to fix it...

**Comment by wbloszyk** [comment]
> It took me some time to merge all the files, shame that I did not do it correctly

I also make many mistake. "Shit happens".

**Pull request merged**
