### PR TITLE
Removed pre sf2.8 bc code

### PR DESCRIPTION
**Pull request by acrobat**
I am targeting this branch, because it's a code cleanup for the 3.x branch.

## Changelog

```markdown
### Removed
- Remove pre sf2.8 bc code
```

## Subject

Some code cleanup after the <sf2.8 dependency change.

### CODE REVIEW

**Comment by acrobat** [comment]
@greg0ire Do I need to do the styleci fixes in a separate commit or in a separate PR?

**Comment by OskarStark** [comment]
@acrobat a separate commit would be enough, thank you

**Comment by acrobat** [comment]
Ok @OskarStark, I've pushed another commit!

**Comment by Soullivaneuh** [comment]
Let's separate StyleCI from here: https://github.com/sonata-project/SonataBlockBundle/pull/419

Please rebase and remove your commit @acrobat

**Comment by acrobat** [comment]
@Soullivaneuh done!

**Comment by Soullivaneuh** [comment]
@acrobat Travis CI is failing, could you please have a look?

**Comment by OskarStark** [comment]
I restarted the failing build, this is was the error:

```
1) Sonata\BlockBundle\Tests\Cache\HttpCacheHandlerTest::testResponseTtlNotAlteredIfNoRenderedBlock
Failed asserting that 83 matches expected 84.
/home/travis/build/sonata-project/SonataBlockBundle/Tests/Cache/HttpCacheHandlerTest.php:52
```

**Comment by acrobat** [comment]
Looks like a random fail indeed, but if this happens regularly we should fix this test

**Comment by Soullivaneuh** [comment]
Thank you @acrobat! :+1:

**Pull request merged**
