### PR TITLE
Fix missing ? in type hints

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because this change respect BC.

## Changelog

```markdown
### Fixed
- missing `?` in type hints where null is default value
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
This should be generate by dev-kit.
https://github.com/sonata-project/dev-kit/blob/master/project/.php_cs.dist.twig#L36

I think `3.x` branch was remove to fast:
https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml#L105-L116

**Comment by phansys** [comment]
>This should be generate by dev-kit.
https://github.com/sonata-project/dev-kit/blob/master/project/.php_cs.dist.twig#L36

I think `3.x` branch was remove to fast:
https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml#L105-L116

Yes, but what I mean is: if we want to ensure any rule we should make it explicit at `.php_cs.dist` (regardless it's currently handled by dev-kit or not).

**Comment by VincentLanglet** [comment]
> I think `3.x` branch was remove to fast:
> https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml#L105-L116

Indeed, since we're still supporting 3.x. Do you want to make a pr ?

**Comment by wbloszyk** [comment]
@VincentLanglet Ca you check it? I'm not sure we `sonata_admin` and `sonata_core` but I think this should be check too.

https://github.com/sonata-project/dev-kit/pull/783

**Comment by wbloszyk** [comment]
Can we merge this?

**Comment by jordisala1991** [comment]
Thank you @wbloszyk

**Pull request merged**
