### PR TITLE
Update to "Your First Block" documentation.

### PR DESCRIPTION
**Pull request by aleksandrmelnikov**
I am targeting this branch, because the documentation update has to do with the block-bundle version 3.2.0. I assume this bundle is available only in the 3.x branch.

## Changelog

```markdown
### Added
- Added documentation about setting up your first block for version 3.2.0 of the block-bundle.
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Oh wow… 37 commits… I think you need to rebase…

**Comment by aleksandrmelnikov** [comment]
To be honest, I have not done very many pull requests via GitHub. Can you give me a suggestion for what I should do?
Close this Pull Request and create a new one with some more steps?

**Comment by greg0ire** [comment]
You should do the following : 

1. Fetch all new commits `git fetch --all`
2. Rebase on what you fetched interactively
  1. `git rebase -i origin/3.x` (assuming `origin` is a git remote that points to this repository, and not your fork)
  2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit
3. Force push to overwrite all this : `git push --force`

**Comment by aleksandrmelnikov** [comment]
Thank you for instructions, I will hopefully get this right soon :)

**Comment by greg0ire** [comment]
I see you tried again, but it looks like you forgot the `--force` option when pushing ;)

**Comment by aleksandrmelnikov** [comment]
Augh, thank you. I went through like 19 merge conflicts and I was hoping that would have done it. I'll try your new instructions. Thank you for the quick response.

**Comment by aleksandrmelnikov** [comment]
Hmm, I feel like I did your instructions on the wrong branch. I did them for 3.x and it was a lot cleaner, but the PR is for patch-1?

**Comment by greg0ire** [comment]
First step is resetting `patch-1` to `3.x`, making sure it's the same again. Step 3 is force pushing patch-1. So step 0 would be: make sure you are on patch-1 : `git checkout patch-1`

**Comment by greg0ire** [comment]
Also, if you want to better understand what is happening, use `git log --graph --decorate --all`. It should give you a better view.

**Comment by greg0ire** [comment]
After step 1, you should be on 150d8d5b1036b758d4f434e3f21ef806ba4e74c2

**Comment by aleksandrmelnikov** [comment]
Thank you kindly for your patient support. I think I got it pushed up correctly now? I totally did miss step 0.

**Comment by greg0ire** [comment]
Yaaaay! Yes you did!

**Comment by greg0ire** [comment]
Please run `git commit --amend`, and change "Defalut" to "Default", and then `git push --force`. Should be a piece of cake now ;)

**Comment by aleksandrmelnikov** [comment]
Of all the things, I even had a typo, hahahaha. But yes, a lot easier now :). Again, I very much appreciate the help.

**Comment by greg0ire** [comment]
And I'm glad you didn't give up! @sonata-project/contributors , please review!

**Comment by aleksandrmelnikov** [comment]
I refused to let my attempt at improving documentation languish ;)

**Comment by greg0ire** [comment]
Way to go!

**Comment by OskarStark** [comment]
I would rather change the setDefaultSettings() to configureOptions() instead of adding a note
what do you think @greg0ire ?

**Comment by greg0ire** [comment]
You're right @OskarStark ! @aleksandrmelnikov , please do that, and optionally invert the note : 

> for block bundle < 3.2, please use …

**Comment by greg0ire** [comment]
ping @aleksandrmelnikov

**Comment by OskarStark** [comment]
I created a new PR in #373

**Pull request closed without merging**
