### PR TITLE
Menu parameter as required

### PR DESCRIPTION
**Pull request by eerison**
## Subject

I am targeting this branch, because {reason}.

## Changelog

```markdown

### Changed
- Changed Menu name settings `required` field from `false` to `true` in `getFormSettingsKeys`
```

### CODE REVIEW

**Comment by eerison** [comment]
This field is required to render Menu

Issue: https://github.com/sonata-project/SonataPageBundle/issues/1495#issuecomment-1269493681

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Can you fix the CI @eerison ?

**Comment by eerison** [comment]
is it missing something 👀 ?

**Comment by VincentLanglet** [comment]
> is it missing something 👀 ?

time ^^

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @eerison

**Pull request merged**
