### PR TITLE
DevKit updates for master branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
@core23 ?

**Comment by core23** [comment]
> @core23 ?

Anything wrong?

**Comment by OskarStark** [comment]
I am just wondering why we are not testing this against `7.4snapshot` anymore

**Comment by core23** [comment]
Should be right now. No idea why this was missing:
https://github.com/sonata-project/dev-kit/blob/master/config/projects.yml#L50-L65

**Comment by OskarStark** [comment]
Ah damn, it **adds** 7.4.... forget it... too early 😄

**Pull request merged**
