### PR TITLE
Manual merge 3.x

### PR DESCRIPTION
**Pull request by jlamur**
:skull_and_crossbones: Don't merge, only approve!

Should I remove deprecated stuff now, @greg0ire @Soullivaneuh?
It could be great, but better if done at every merge, which is not possible with SonataCI, of course.

### CODE REVIEW

**Comment by greg0ire** [comment]
You can, I have no objections

**Comment by Soullivaneuh** [comment]
@jlamur @greg0ire IMHO, it would be better to focus on the branch merging only for clarity.

**Comment by greg0ire** [comment]
Anyway, please fix StyleCI

**Comment by Soullivaneuh** [comment]
StyleCI fixed here: https://github.com/sonata-project/SonataBlockBundle/pull/419

**Comment by jlamur** [comment]
I need to amend the merge commit to include styleci fixes. I'm going to do it now.

**Comment by jlamur** [comment]
Merge commit updated.

**Pull request merged**
