### PR TITLE
Add support for sonata/cache 2

### PR DESCRIPTION
**Pull request by greg0ire**
I am targeting this branch, because this is BC

## Changelog
```markdown
### Added
- support for sonata/cache 2
```

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Is this finally compatible with both version without any modification?

**Comment by greg0ire** [comment]
I think you are confusing with https://github.com/sonata-project/SonataCacheBundle/pull/150

**Comment by Soullivaneuh** [comment]
Oh right.

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Pull request merged**
