### PR TITLE
Add container dashboard block

### PR DESCRIPTION
**Pull request by qsomazzi**

### CODE REVIEW

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by rande** [comment]
ok to test

**Comment by Soullivaneuh** [comment]
@qsomazzi Is this BC? Default parameter seems to be completely changed.

**Comment by rande** [comment]
Yes; it is :)

**Pull request merged**
