### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**
Just approve, please do not merge.

### CODE REVIEW

**Comment by greg0ire** [comment]
```
1) Sonata\BlockBundle\Tests\Cache\HttpCacheHandlerTest::testResponseTtlNotAlteredIfNoRenderedBlock
Failed asserting that 83 matches expected 84.
/home/travis/build/sonata-project/SonataBlockBundle/tests/Cache/HttpCacheHandlerTest.php:54
```

:confused:

**Comment by kunicmarko20** [comment]
Restarted the build 😅

**Comment by greg0ire** [comment]
You could have restarted the only job that was failing :P The test deals with time, so that's probably a good idea to restart it.

**Comment by kunicmarko20** [comment]
I am on my phone and restard build was the first button 😄 Will check before restarting next time

**Comment by greg0ire** [comment]
Well it passes this time, good job!

**Pull request merged**
