### PR TITLE
quote strings with meta-characters

### LINKED ISSUE #252: Documentation is broken
Build is not passing, because something is wrong with sphinx

see sphinx-doc/sphinx#2264

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #252

### CODE REVIEW

**Comment by core23** [comment]
Can you please rebase? @greg0ire

**Comment by greg0ire** [comment]
What do you mean ? I am already based on the lastest commit of `sonata-project/SonataBlockBundle/2.3`

**Comment by core23** [comment]
There are 2 commits in the PR.

**Comment by greg0ire** [comment]
Yeah, one of them is yours, and is necessary to fix the build ;) I backported it from master

**Comment by greg0ire** [comment]
Can't figure out why Scrutinizer fails though… any idea?

**Comment by core23** [comment]
Think we should create a seperate PR for this.

No idea what's wrong with Scrutinizer :/

**Comment by greg0ire** [comment]
A separate PR ? Isn't it the same concern (fixing the build) ?

**Comment by greg0ire** [comment]
Looks like there is some kind of conflict between sonata block dev 2.3 and stable versions required by the… admin-bundle -___- . Can someone explain what scrutinizer is doing ? @rande @pulzarraider @OskarStark ?

**Comment by OskarStark** [comment]
i ignore the scrutiizer in most cases, but IMO it does something like static code analysis

i would merge this PR @core23

**Comment by greg0ire** [comment]
Yeah @core23, please merge. Having two commits from different authors in the same PR is completely fine : you can still revert one commit and not the other if you want.

**Comment by core23** [comment]
Thank you @greg0ire

**Comment by OskarStark** [comment]
:+1:

**Pull request merged**
