### PR TITLE
Dropping support for symfony < 3.4

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

This is the same thing as https://github.com/sonata-project/SonataAdminBundle/pull/5733, dropping support of Symfony < 3.4 and >= 4, < 4.2

I am targeting this branch, because these changes respect BC.

## Changelog

```markdown
### Removed
- Support for Symfony < 3.4
- Support for Symfony >= 4, < 4.2
```

### CODE REVIEW

**Comment by greg0ire** [comment]
For the `prefer-lowest` build, Composer fails to solve the issue given the current constraint in a timely manner. You may try bumping to the latest `3.4` and `4.2`, it might help.

**Comment by core23** [comment]
You could also try to bump the sonata deps, e.g. the core bundle

**Comment by core23** [comment]
Maybe we still need this? https://github.com/sonata-project/dev-kit/pull/509

**Comment by OskarStark** [comment]
But this was already merged and deployed

**Comment by core23** [comment]
> But this was already merged and deployed

That's true, but it looks like we got an other edge case when we use higher versions :|

**Comment by franmomu** [comment]
If I remove `"sonata-project/admin-bundle"` from `composer.json` locally, it just takes: `Dependency resolution completed in 0.589 seconds`

**Comment by core23** [comment]
> If I remove `"sonata-project/admin-bundle"` from `composer.json` locally, it just takes: `Dependency resolution completed in 0.589 seconds`

:/ Maybe you could change the base branch to `master`. I want to release a new major version without the admin dependency soon.

**Comment by franmomu** [comment]
I've just added `"symfony/symfony": "^3.4 || ^4.2"` to see if it works, so... it looks like is because of requiring version 2.8 of symfony/x packages... so what about adding `SYMFONY=3.4.*` env to:
```
- php: '7.1'
  env: COMPOSER_FLAGS="--prefer-lowest"
```

**Comment by core23** [comment]
Here is a port for the major: https://github.com/sonata-project/SonataBlockBundle/pull/653

**Comment by greg0ire** [comment]
@franmomu maybe we can close this since the port works and we are going to release the block bundle v3 really soon.

**Comment by franmomu** [comment]
Ok, perfect!

**Pull request closed without merging**
