### PR TITLE
Remove doctrine common

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Not sure if it is safe to do this change or we have to do it different.

**Comment by jordisala1991** [comment]
Wdyt @VincentLanglet ?

**Review by VincentLanglet — COMMENTED** [review]
I'm not sure about it, ClassUtils was used for Proxy classes.
If the blocks are doctrine entities, it may won't work.

In SonataPage we have blocks as entities 
https://github.com/sonata-project/SonataPageBundle/blob/4.x/src/Entity/BaseBlock.php
so this might be an issue here...

I dunno what's the doctrine recommendation...

**Comment by jordisala1991** [comment]
I think with the new proxy system on the orm it might not be an issue anymore, but it is only an opt in on 2.14 sf 6.2 and persistence 3.1, it might not be safe indeed.

Another option is to port the code to avoid the dep, wdyt?

**Comment by VincentLanglet** [comment]
To port this in BlockBundle we will still need to add `doctrine-persistence` as a dependency.

If we do this, we could follow the following suggestion: https://github.com/doctrine/persistence/pull/326#issuecomment-1374466942

**Comment by jordisala1991** [comment]
I think we should wait more for this change.

**Pull request closed without merging**
