### PR TITLE
remove * (asterisk) in profiler/profiler-toolbar

### PR DESCRIPTION
**Pull request by OskarStark**
remove * (asterisk) because, no one knows, that this indicates, that events were thrown

### CODE REVIEW

**Comment by OskarStark** [comment]
Fixes #229

**Comment by OskarStark** [comment]
@Soullivaneuh do you have an idea, why travis failed?

**Comment by Soullivaneuh** [comment]
CS need to be ran on master.

BTW, this `*` seems to be related to events count.

No sure this should be removed.

Please wait @rande decision.

**Comment by OskarStark** [comment]
@Soullivaneuh CS problem looks like the other ones.
I created an issue here FriendsOfPHP/PHP-CS-Fixer#1450

But now with my change, the current and the new redesigned toolbar looks the same, as we don't show the asterisk in the new markup here:
https://github.com/sonata-project/SonataBlockBundle/pull/230/files#diff-8d1d2fb5d440bda24d37396fb7790e89R18

So this looks to me, that someone already decided to remove the asterisk for the new version...

**Comment by OskarStark** [comment]
restarted travis

**Comment by core23** [comment]
Can you rebase?

**Comment by core23** [comment]
Ping @OskarStark

**Comment by core23** [comment]
Please have a look at this @OskarStark

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
