### PR TITLE
Bump cache

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is a preparation for the next major release.

## Changelog

```markdown
### Removed
- Remove support for sonata cache 1.x
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked until https://github.com/sonata-project/dev-kit/pull/511 is deployed (should happen tonight?)

**Comment by OskarStark** [comment]
Done, please rebase

**Comment by core23** [comment]
Done @OskarStark

**Comment by greg0ire** [comment]
Thanks @core23!

**Pull request merged**
