### PR TITLE
Corrige a typo in a parameter name.

### PR DESCRIPTION
**Pull request by JonathanBaudoin**
I am targeting this branch, because [the last commit](https://github.com/sonata-project/SonataBlockBundle/commit/555e119675604efc454e5eb8fba115d33f4ac221#diff-cf5595281888e87b6d494c89929b9757R177) add an issue with a bad parameter name.

## CHANGELOG
```markdown
### Fixed
- bad parameter name
```

### CODE REVIEW

**Comment by OskarStark** [comment]
Are you sure this is correct?

cc @core23

**Comment by core23** [comment]
Must be a local merge conflict, sry :(

Thanks @JonathanBaudoin

**Comment by OskarStark** [comment]
Thank you @JonathanBaudoin

**Comment by JonathanBaudoin** [comment]
Thanks to **you** guys. I use Sonata bundles every days in my company, that's the least I can do.

**Comment by greg0ire** [comment]
Since the bug wasn't released, I'm removing the changelog.

**Pull request merged**
