### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**
Don't merge, just approve.

### CODE REVIEW

**Comment by greg0ire** [comment]
@jordisala1991 yes. Master does not need this complex condition.

**Comment by jordisala1991** [comment]
I trust in you. Take into account that master is compatible with 2.8 still

**Comment by greg0ire** [comment]
> I trust in you. Take into account that master is compatible with 2.8 still

Hmmm then maybe you shouldn't trust me 😅

**Comment by greg0ire** [comment]
@jordisala1991 this one should look better :P

**Pull request merged**
