### PR TITLE
Add missing italian translations

### PR DESCRIPTION
**Pull request by gremo**
I am targeting this branch, because this is an improvement.

## Changelog

```markdown
### Added
- Missing italian translations
```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
I think changelog should be fixed instead of added.

**Comment by gremo** [comment]
@kunicmarko20 not changing existing translations but adding missing ones.

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/4937#issuecomment-364067645

**Comment by greg0ire** [comment]
Thanks @gremo

**Pull request merged**
