### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by core23**
This is just a test to resolve the conflicts of #631

### CODE REVIEW

**Comment by core23** [comment]
Adding `psr/cache-implementation` causes the problem. Maybe we could remove this dependency? @phansys

**Comment by phansys** [comment]
`psr/cache-implementation` causes the problem because it is provided by `symfony/cache: 4.3.4`, which has a requirement against [`php: ^7.1.3`]( https://packagist.org/packages/symfony/cache#v4.3.4), while `sonata-project/block-bundle` at `master` branch has the requirement `php: ^7.3`.
BTW, I didn't analyzed yet if requirement for `psr/cache-implementation` can be dropped.

**Comment by core23** [comment]
> `psr/cache-implementation` [...], which has a requirement against [`php: ^7.1.3`](https://packagist.org/packages/symfony/cache#v4.3.4), while `sonata-project/block-bundle` at `master` branch has the requirement `php: ^7.3`.

I don't get the problem. We require `^7.3`, while symfony is requiring `^7.1.3`. Travis runs on PHP 7.3, so this should match both requirements 🤔

**Comment by phansys** [comment]
> > `psr/cache-implementation` [...], which has a requirement against [`php: ^7.1.3`](https://packagist.org/packages/symfony/cache#v4.3.4), while `sonata-project/block-bundle` at `master` branch has the requirement `php: ^7.3`.
> 
> I don't get the problem. We require `^7.3`, while symfony is requiring `^7.1.3`. Travis runs on PHP 7.3, so this should match both requirements

You're right @core23, I misread the requirement as `~7.1.3`, my apologies.
I think we can analyze if `psr/cache-implementation` could be removed, but I also think that we should have a clear idea why we need to do that.

**Comment by core23** [comment]
> I think we can analyze if `psr/cache-implementation` could be removed, but I also think that we should have a clear idea why we need to do that.

The dependency was added with #628. The original idea was to force the user to use a cache, which is wrong. The bundle can work without a cache. 

The non-psr cache was optional: https://github.com/sonata-project/SonataBlockBundle/blob/3.17.0/src/Templating/Helper/BlockHelper.php#L89

**Comment by phansys** [comment]
I agree with the proposed solution, just don't like to not understand why the dependency conflict is in place.

**Pull request closed without merging**
