### PR TITLE
Deprecate BaseBlockService and BlockAdminServiceInterface

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Added
- created `Sonata\BlockBundle\Block\Service\AbstractAdminBlockService` class
- created `Sonata\BlockBundle\Block\Service\AbstractBlockService` class
- created `Sonata\BlockBundle\Block\Service\AdminBlockServiceInterface` class
- created `Sonata\BlockBundle\Block\Service\BlockServiceInterface` class

### Deprecated
- the class `Sonata\BlockBundle\Block\AbstractBlockService` is deprecated
- the class `Sonata\BlockBundle\Block\BaseBlockService` is deprecated
- the class `Sonata\BlockBundle\Block\BlockAdminServiceInterface` is deprecated
- the class `Sonata\BlockBundle\Block\BlockServiceInterface` is deprecated

```

## To do

- [X] Update the tests
- [x] Update the documentation
- [X] Add an upgrade note

## Subject

The class BaseBlockService doesn't match the correct naming convention and starts with Base instead of Abstract. The BaseBlockService class contains special methods for the admin bundle, so should be moved to special class.

This is a rebase of #328, but the inheritance of the `BlockServiceInterface` is switch, so the `BlockRenderer::addMetaInformation` method should work.

### CODE REVIEW

**Comment by greg0ire** [comment]
wat

Sorry, but this one is a bit hard to get.

1. Why would you rebase something that is already merged?
2. What do you mean by "but the inheritance of the BlockServiceInterface is switch"?
3. Why is the changelog the same as #308

**Comment by core23** [comment]
The changelog is the same, because it's nearly the same as #308.

The only difference between the PRs is in the `Sonata\BlockBundle\Block\ServiceBlockServiceInterface` and `Sonata\BlockBundle\Block\BlockServiceInterface\Sonata\BlockBundle\Block\BlockServiceInterface` interfaces.

The interheritance is switched, so old code would work when using the new interface.

**Comment by greg0ire** [comment]
Thanks, I get it now,  LGTM!

**Comment by core23** [comment]
@OskarStark Can you give a second review?

**Comment by OskarStark** [comment]
Thank you @core23 👍  i squashed the commits into one

**Pull request merged**
