### PR TITLE
colorize toolbar label if one or more blocks were rendered

### PR DESCRIPTION
**Pull request by mvhirsch**
@OskarStark  As mentioned in #229.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could we have a before/after screenshot?

Please take a look to SF 2.8 toolbar too.

**Comment by OskarStark** [comment]
bildschirmfoto 2015-10-14 um 16 05 04
bildschirmfoto 2015-10-14 um 16 05 08

before it was grey :smile: 

@Soullivaneuh i would like to merge this PR as it is.

IMO we have to check and open a separate issue/PR for adjustments for 2.8 toolbar

Thank you @mvhirsch

**Comment by Soullivaneuh** [comment]
> IMO we have to check and open a separate issue/PR for adjustments for 2.8 toolbar

No. 2.8 compatibility is already here. We can't accept broken PR for that. Both need to be handled.

**Comment by OskarStark** [comment]
Ok, but i don't understand how adding a class name to a span could broke the panel...

can you explain more?

**Comment by Soullivaneuh** [comment]
See this line: https://github.com/sonata-project/SonataBlockBundle/pull/231/files#diff-8d1d2fb5d440bda24d37396fb7790e89R7

Behavior should be the same. So we have to check this.

**Comment by OskarStark** [comment]
good catch @Soullivaneuh 

@mvhirsch can you please also handle the 2.8 version?

**Comment by mvhirsch** [comment]
@OskarStark @Soullivaneuh I don't think we need to colorize in the new symfony toolbar.
We should only colorize warnings/errors according to this blog entry:

http://symfony.com/blog/new-in-symfony-2-8-redesigned-web-debug-toolbar

> [...] Another important difference is the way errors and warnings are displayed. Previously we displayed just a small green/yellow/red icon, whereas now we change the entire panel background to easily spot when some error happens [...]

**Comment by mvhirsch** [comment]
What do you think @OskarStark @Soullivaneuh?

**Comment by OskarStark** [comment]
:+1: @mvhirsch

**Comment by Soullivaneuh** [comment]
I don't know if we really should colorize it. See doctrine request, no colors.

Green color seems to be used for successful stuff like ajax request and more.

Not sure if this should be applied here.

ping @rande @sonata-project/contributors

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
