### PR TITLE
4.3.0

### PR DESCRIPTION
**Pull request by phansys**

### CODE REVIEW

**Comment by jordisala1991** [comment]
I think we need to check 2 things:

1. 3.x is merged on 4.x
2. add the missing changelog from bugfixes / features from 3.x

This release is a bit harder than a normal one

**Comment by jordisala1991** [comment]
I think the point 1. is done already

**Comment by jordisala1991** [comment]
And for the second point I think we should only mention the support for doctrine/common 3

**Comment by phansys** [comment]
>I think the point 1. is done already

Yes, currently there is nothing to compare [between 4.x and 3.x](https://github.com/sonata-project/SonataBlockBundle/compare/4.x...3.x).

**Comment by phansys** [comment]
>And for the second point I think we should only mention the support for doctrine/common 3

I've updated the changelog through `release` command, with some minimal changes to target the `4.x` branch. Is this mention omitted in the PR where the change was introduced?

**Comment by jordisala1991** [comment]
I dont think so but it was for a Pr targeting 3.x branch and the command is not able to understand that a release for 4.x might contain changelog from Prs on 3.x branch

**Comment by phansys** [comment]
I just add the [changelog comment](https://github.com/sonata-project/SonataBlockBundle/pull/725/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6-R7) from #710. Please, let me know if there is something else to improve.

**Comment by jordisala1991** [comment]
I think it is great, thank you :)

**Pull request merged**
