### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@core23 I fixed an issue with `FormMapper` in 350e728 , but there is still an issue with the admin bundle no longer being present:

```
1) Sonata\BlockBundle\Tests\TextBlockListenerTest::testEventWithAdmin
Cannot stub or mock class or interface "Sonata\AdminBundle\Admin\AdminInterface" which does not exist
```

Also, there is this warning:

```
2) Warning
The data provider specified for Sonata\BlockBundle\Tests\Resources\XliffTest::testXliff is invalid.
Trying to invoke private method Sonata\BlockBundle\Tests\Resources\XliffTest::getXliffPaths() from scope ReflectionMethod

```

**Comment by greg0ire** [comment]
Ping @core23

**Comment by core23** [comment]
I think we can remove the `TextBlockListener` and `TextBlockListenerTest` classes

**Comment by core23** [comment]
`XliffTest::getXliffPaths` must be public

**Pull request merged**
