### PR TITLE
Deprecated BaseCommand

### PR DESCRIPTION
**Pull request by core23**
## Subject

This abstract class in only used once.

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Deprecated
- Deprecated `BaseCommand` class

```

### CODE REVIEW

**Comment by core23** [comment]
> Shouldn't we add the corresponding `trigger_error()` call with the `E_USER_DEPRECATED` as the error type before the class declaration?

This would trigger every time, because this class is used by `DebugBlocksCommand`

**Comment by phansys** [comment]
Aren't these example cases resulting in the same behavior?
https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Block/AbstractBlockService.php#L16-L21

https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Block/BaseBlockService.php#L18-L23

**Comment by core23** [comment]
> Aren't these example cases resulting in the same behavior?
> 
> https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Block/AbstractBlockService.php#L16-L21
> 
> https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Block/BaseBlockService.php#L18-L23

Yes, you're right. We should fix this somehow :|

**Comment by phansys** [comment]
Maybe I'm missing something, but AFAIK these errors are only triggered when the file is loaded, and thanks the autoloading it occurs just once.

**Comment by core23** [comment]
> Maybe I'm missing something, but AFAIK these errors are only triggered when the file is loaded, and thanks the autoloading it occurs just once.

That's right, but the user gets a deprecation warning without doing anything wrong

**Pull request merged**
