### PR TITLE
Migrate namespace for InlineConstraint

### PR DESCRIPTION
**Pull request by rande**

### CODE REVIEW

**Comment by rande** [comment]
@dbu @lsmith77 Hello, there is a WIP to remove a dependency to the AdminBundle. This is a major BC break in interface however as you can see it is pretty easy to fix.

What do you think ?

**Comment by lsmith77** [comment]
the next version will be 2.0 for us anyway

**Comment by rande** [comment]
@lsmith77 ok so it is time to make a BC break ;)

**Comment by lsmith77** [comment]
yeah .. break away! :)

**Comment by rande** [comment]
done https://github.com/sonata-project/SonataBlockBundle/commit/06fac2531ac872ea94a650a345331e14c4da9eb0

**Pull request closed without merging**
