### PR TITLE
Fix argument 1 passed to `DebugBlocksCommand::__construct()` at `commands.xml`

### LINKED ISSUE #583: Command name "" is invalid due to DebugBlocksCommand constructor
Hi, 

When executing:

`php bin/console --env=prod `

I get this eror:

```
16:54:07 ERROR [console] Error thrown while running command "--env=prod". Message: "Command name "" is invalid." ["exception" => Symfony\Component\Console\Exception\InvalidArgumentException { …},"command" => "--env=prod","message" => "Command name "" is invalid."] ["environment" => "PROD","user" => ["id" => 0,"username" => "anon."]]

Command name "" is invalid.
```
That seems to be caused by the XML in this [commit](https://github.com/sonata-project/SonataBlockBundle/commit/2d85ede21816699a342d9f1d094cfbf1b0ff706b#diff-c938dc34d0603ae0938bd26f96b2d048). witch has no name as argument for the Command 

Fixin block-bundle to 3.15.0 solves the issue

Here is the debug level vervose resposne:

```
In Command.php line 661:
                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  Command name "" is invalid.                                     
                                                                  

Exception trace:
 () at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:661
 Symfony\Component\Console\Command\Command->validateName() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:423
 Symfony\Component\Console\Command\Command->setName() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:74
 Symfony\Component\Console\Command\Command->__construct() at /var/www/html/vendor/sonata-project/block-bundle/src/Command/BaseCommand.php:41
 Sonata\BlockBundle\Command\BaseCommand->__construct() at /var/www/html/var/cache/prod/ContainerJ0jvzbc/getDebugBlocksCommandService.php:8
 require() at /var/www/html/var/cache/prod/ContainerJ0jvzbc/oposProdProjectContainer.php:3140
 ContainerJ0jvzbc\oposProdProjectContainer->load() at /var/www/html/var/cache/prod/ContainerJ0jvzbc/getConsole_CommandLoaderService.php:9
 ContainerJ0jvzbc\oposProdProjectContainer->{closure}() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ServiceLocator.php:64
 Symfony\Component\DependencyInjection\ServiceLocator->get() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/CommandLoader/ContainerCommandLoader.php:37
 Symfony\Component\Console\CommandLoader\ContainerCommandLoader->get() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:519
 Symfony\Component\Console\Application->has() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:692
 Symfony\Component\Console\Application->all() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:122
 Symfony\Bundle\FrameworkBundle\Console\Application->all() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Descriptor/ApplicationDescription.php:103
 Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Descriptor/ApplicationDescription.php:76
 Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Descriptor/TextDescriptor.php:194
 Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Descriptor/Descriptor.php:55
 Symfony\Component\Console\Descriptor\Descriptor->describe() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/DescriptorHelper.php:69
 Symfony\Component\Console\Helper\DescriptorHelper->describe() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/ListCommand.php:75
 Symfony\Component\Console\Command\ListCommand->execute() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:987
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:28

```

### Environment

```
PHP 7.2.19 (cli) (built: Jun 17 2019 22:32:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```

#### Sonata packages

```
sonata-project/block-bundle        3.x-dev f18c789 dev-master 46e2777 Symfony SonataBlockBundle         
sonata-project/cache               2.x-dev c81334f dev-master ba5a1a7 Cache library
sonata-project/core-bundle         3.17.0          dev-master b32452e Symfony SonataCoreBundle
sonata-project/datagrid-bundle     2.x-dev d13faff dev-master 0578dbc Symfony SonataDatagridBundle
sonata-project/doctrine-extensions 1.x-dev 5c9bfa6 dev-master 8fdcd48 Doctrine2 behavioral extensions
sonata-project/intl-bundle         2.x-dev 8722cc1 dev-master 20c40e8 Symfony SonataIntlBundle

```

### PR DESCRIPTION
**Pull request by phansys**
## Subject

I am targeting this branch, because this change respects BC.

Closes #583.

## Changelog

```markdown
### Fixed
- Argument 1 passed to `DebugBlocksCommand::__construct()` at `commands.xml` was an empty string instead of `null`.
```

### CODE REVIEW

**Comment by greg0ire** [comment]
I just restarted the failing CI job to see if it is transient.

**Comment by greg0ire** [comment]
It was. Thanks @phansys !

**Comment by core23** [comment]
Maybe we should add some tests which will check if the application context can be initialized. 

Not sure if this is possible in symfony, but you can create such tests in Java spring 😺

**Comment by greg0ire** [comment]
It's completely possible to write a smoke test that iterates on all services and attempts to instantiate them.

**Pull request merged**
